server {
    listen 80;
    server_name localhost;

    # Handle client-side routing and static assets
    location / {
        # Proxy requests to the Next.js app
        proxy_pass http://nextjs_app:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Specifically handle Next.js static files for better performance
    location /_next/static {
        proxy_cache STATIC;
        proxy_pass http://nextjs_app:3000/_next/static;
    }

    location /_next/image {
        proxy_pass http://nextjs_app:3000/_next/image;
        proxy_set_header Host $host;
    }
}
